export type CoverTone =
  | "ember"
  | "rust"
  | "moss"
  | "sea"
  | "night"
  | "bone"
  | "wine"
  | "steel"
  | "sand"
  | "frost"
  | "copper"
  | "pine"
  | "slate"
  | "ash"
  | "oxblood"
  | "charcoal";

export type Genre =
  | "Action"
  | "RPG"
  | "Shooter"
  | "Horror"
  | "Racing"
  | "Adventure"
  | "Soulslike"
  | "Platformer"
  | "Strategy"
  | "Fighting"
  | "Co-op"
  | "Open world"
  | "Sports";

export type Mood = "story" | "challenge" | "friends" | "chill" | "scare";

export type Verdict = "buy" | "wait" | "skip" | "soon";

export type Game = {
  slug: string;
  title: string;
  year: number;
  publisher: string;
  genres: Genre[];
  moods: Mood[];
  msrp: number;
  street: number;
  hoursMain: number;
  hoursExtra: number;
  hoursComp: number;
  quality: number;
  plat: 1 | 2 | 3 | 4 | 5;
  exclusive: boolean;
  comingSoon?: boolean;
  estimated?: boolean;
  note: string;
  cover: CoverTone;
};

import { EXPANDED_GAMES } from "@/lib/catalog-expansion";

const BASE_GAMES: Game[] = [
  {
    slug: "elden-ring",
    title: "Elden Ring",
    year: 2022,
    publisher: "FromSoftware",
    genres: ["Soulslike", "RPG", "Open world"],
    moods: ["challenge"],
    msrp: 60,
    street: 40,
    hoursMain: 55,
    hoursExtra: 90,
    hoursComp: 130,
    quality: 10,
    plat: 4,
    exclusive: false,
    note: "The rare $70-class game that still feels cheap at street price. A whole hobby in one disc.",
    cover: "night",
  },
  {
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    year: 2023,
    publisher: "Larian",
    genres: ["RPG", "Adventure"],
    moods: ["story", "friends"],
    msrp: 70,
    street: 50,
    hoursMain: 75,
    hoursExtra: 110,
    hoursComp: 150,
    quality: 10,
    plat: 3,
    exclusive: false,
    note: "Campaigns measured in weeks, not weekends. Co-op if you want it, solo if you don't.",
    cover: "wine",
  },
  {
    slug: "astro-bot",
    title: "Astro Bot",
    year: 2024,
    publisher: "Team Asobi",
    genres: ["Platformer", "Adventure"],
    moods: ["chill"],
    msrp: 70,
    street: 50,
    hoursMain: 12,
    hoursExtra: 16,
    hoursComp: 22,
    quality: 10,
    plat: 2,
    exclusive: true,
    note: "Short. Perfect. The best argument for owning a PS5 that isn't a $70 cinematic.",
    cover: "sand",
  },
  {
    slug: "god-of-war-ragnarok",
    title: "God of War Ragnarok",
    year: 2022,
    publisher: "Santa Monica Studio",
    genres: ["Action", "Adventure"],
    moods: ["story"],
    msrp: 70,
    street: 40,
    hoursMain: 21,
    hoursExtra: 32,
    hoursComp: 50,
    quality: 9,
    plat: 2,
    exclusive: true,
    note: "Street price finally matches the campaign length. Buy the disc edition if you can find it cheap.",
    cover: "ember",
  },
  {
    slug: "spider-man-2",
    title: "Marvel's Spider-Man 2",
    year: 2023,
    publisher: "Insomniac",
    genres: ["Action", "Open world"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 40,
    hoursMain: 17,
    hoursExtra: 24,
    hoursComp: 32,
    quality: 8,
    plat: 2,
    exclusive: true,
    note: "A great weekend swing. Full price was steep for the length; $40 is the honest number.",
    cover: "rust",
  },
  {
    slug: "ghost-of-tsushima",
    title: "Ghost of Tsushima Director's Cut",
    year: 2021,
    publisher: "Sucker Punch",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 30,
    hoursMain: 25,
    hoursExtra: 40,
    hoursComp: 55,
    quality: 9,
    plat: 2,
    exclusive: true,
    note: "One of the best dollars-per-hour on the system if you like a quiet, pretty stabbing simulator.",
    cover: "moss",
  },
  {
    slug: "ghost-of-yotei",
    title: "Ghost of Yotei",
    year: 2025,
    publisher: "Sucker Punch",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["story"],
    msrp: 70,
    street: 70,
    hoursMain: 22,
    hoursExtra: 38,
    hoursComp: 50,
    quality: 8,
    plat: 2,
    exclusive: true,
    note: "Beautiful, familiar, still full price. Wait for the first deep sale unless you loved Tsushima.",
    cover: "frost",
  },
  {
    slug: "black-myth-wukong",
    title: "Black Myth: Wukong",
    year: 2024,
    publisher: "Game Science",
    genres: ["Action", "Soulslike"],
    moods: ["challenge"],
    msrp: 60,
    street: 45,
    hoursMain: 22,
    hoursExtra: 35,
    hoursComp: 48,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "Spectacle with a real campaign underneath. Better after a discount, still not a trap at $45.",
    cover: "copper",
  },
  {
    slug: "stellar-blade",
    title: "Stellar Blade",
    year: 2024,
    publisher: "Shift Up",
    genres: ["Action", "Adventure"],
    moods: ["challenge"],
    msrp: 70,
    street: 40,
    hoursMain: 19,
    hoursExtra: 28,
    hoursComp: 40,
    quality: 8,
    plat: 3,
    exclusive: true,
    note: "A proper action game, not a demo. Street price is where it belongs.",
    cover: "steel",
  },
  {
    slug: "ff7-rebirth",
    title: "Final Fantasy VII Rebirth",
    year: 2024,
    publisher: "Square Enix",
    genres: ["RPG", "Adventure"],
    moods: ["story"],
    msrp: 70,
    street: 45,
    hoursMain: 38,
    hoursExtra: 58,
    hoursComp: 85,
    quality: 9,
    plat: 4,
    exclusive: true,
    note: "A long, expensive-feeling RPG that actually is long. Platinum is a second job.",
    cover: "sea",
  },
  {
    slug: "tlou-1",
    title: "The Last of Us Part I",
    year: 2022,
    publisher: "Naughty Dog",
    genres: ["Adventure", "Horror", "Action"],
    moods: ["story", "scare"],
    msrp: 70,
    street: 25,
    hoursMain: 14,
    hoursExtra: 17,
    hoursComp: 22,
    quality: 9,
    plat: 3,
    exclusive: true,
    note: "A film you play. Never worth $70 for a 14-hour story. At $25 it is required reading.",
    cover: "ash",
  },
  {
    slug: "tlou-2",
    title: "The Last of Us Part II Remastered",
    year: 2024,
    publisher: "Naughty Dog",
    genres: ["Adventure", "Horror", "Action"],
    moods: ["story", "scare"],
    msrp: 50,
    street: 30,
    hoursMain: 24,
    hoursExtra: 32,
    hoursComp: 42,
    quality: 9,
    plat: 4,
    exclusive: true,
    note: "Longer, meaner, and a better rate than Part I. Platinum is nasty on purpose.",
    cover: "charcoal",
  },
  {
    slug: "horizon-fw",
    title: "Horizon Forbidden West Complete",
    year: 2022,
    publisher: "Guerrilla",
    genres: ["Action", "Open world", "RPG"],
    moods: ["story", "chill"],
    msrp: 50,
    street: 25,
    hoursMain: 30,
    hoursExtra: 50,
    hoursComp: 75,
    quality: 8,
    plat: 2,
    exclusive: true,
    note: "The complete edition at $25 is one of the quiet best buys on PS5.",
    cover: "pine",
  },
  {
    slug: "returnal",
    title: "Returnal",
    year: 2021,
    publisher: "Housemarque",
    genres: ["Shooter", "Action"],
    moods: ["challenge"],
    msrp: 70,
    street: 20,
    hoursMain: 16,
    hoursExtra: 24,
    hoursComp: 40,
    quality: 9,
    plat: 5,
    exclusive: true,
    note: "A masterpiece that launched at the wrong price. $20 is a gift. Platinum is not.",
    cover: "frost",
  },
  {
    slug: "demons-souls",
    title: "Demon's Souls",
    year: 2020,
    publisher: "Bluepoint",
    genres: ["Soulslike", "RPG"],
    moods: ["challenge"],
    msrp: 70,
    street: 25,
    hoursMain: 22,
    hoursExtra: 30,
    hoursComp: 45,
    quality: 8,
    plat: 4,
    exclusive: true,
    note: "Still the prettiest From-like on the system. Wait if you already have Elden Ring unfinished.",
    cover: "bone",
  },
  {
    slug: "gran-turismo-7",
    title: "Gran Turismo 7",
    year: 2022,
    publisher: "Polyphony",
    genres: ["Racing"],
    moods: ["chill"],
    msrp: 70,
    street: 35,
    hoursMain: 20,
    hoursExtra: 60,
    hoursComp: 120,
    quality: 8,
    plat: 5,
    exclusive: true,
    note: "A garage, not a campaign. Hours go sideways if you like cars. Platinum is a second mortgage.",
    cover: "steel",
  },
  {
    slug: "silent-hill-2",
    title: "Silent Hill 2",
    year: 2024,
    publisher: "Bloober Team",
    genres: ["Horror", "Adventure"],
    moods: ["scare", "story"],
    msrp: 70,
    street: 50,
    hoursMain: 16,
    hoursExtra: 22,
    hoursComp: 30,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Worth it if horror is the point. Full price for 16 hours only makes sense if you will replay it.",
    cover: "night",
  },
  {
    slug: "indiana-jones",
    title: "Indiana Jones and the Great Circle",
    year: 2024,
    publisher: "MachineGames",
    genres: ["Adventure", "Action"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 45,
    hoursMain: 17,
    hoursExtra: 24,
    hoursComp: 32,
    quality: 8,
    plat: 2,
    exclusive: false,
    note: "A classy romp that feels like a rental at $70 and a keep at $40.",
    cover: "sand",
  },
  {
    slug: "expedition-33",
    title: "Clair Obscur: Expedition 33",
    year: 2025,
    publisher: "Sandfall",
    genres: ["RPG", "Adventure"],
    moods: ["story", "challenge"],
    msrp: 50,
    street: 50,
    hoursMain: 25,
    hoursExtra: 38,
    hoursComp: 50,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Priced like an indie, structured like a 2006 JRPG in the best way. Easy buy.",
    cover: "wine",
  },
  {
    slug: "kcd2",
    title: "Kingdom Come: Deliverance II",
    year: 2025,
    publisher: "Warhorse",
    genres: ["RPG", "Open world", "Adventure"],
    moods: ["story", "challenge"],
    msrp: 60,
    street: 50,
    hoursMain: 38,
    hoursExtra: 65,
    hoursComp: 95,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "A long, muddy novel. If the first one bounced you, this still might. If it clicked, this is a steal.",
    cover: "rust",
  },
  {
    slug: "monster-hunter-wilds",
    title: "Monster Hunter Wilds",
    year: 2025,
    publisher: "Capcom",
    genres: ["Action", "Co-op", "RPG"],
    moods: ["friends", "challenge"],
    msrp: 70,
    street: 50,
    hoursMain: 35,
    hoursExtra: 80,
    hoursComp: 140,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "The hours are real if you hunt. If you bounce after the story, it becomes a $50 demo.",
    cover: "ember",
  },
  {
    slug: "ac-shadows",
    title: "Assassin's Creed Shadows",
    year: 2025,
    publisher: "Ubisoft",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["chill", "story"],
    msrp: 70,
    street: 40,
    hoursMain: 30,
    hoursExtra: 50,
    hoursComp: 75,
    quality: 7,
    plat: 2,
    exclusive: false,
    note: "A lot of map, a familiar loop. Never pay launch. $40 is the conversation.",
    cover: "moss",
  },
  {
    slug: "split-fiction",
    title: "Split Fiction",
    year: 2025,
    publisher: "Hazelight",
    genres: ["Adventure", "Co-op", "Platformer"],
    moods: ["friends"],
    msrp: 50,
    street: 40,
    hoursMain: 10,
    hoursExtra: 12,
    hoursComp: 16,
    quality: 9,
    plat: 2,
    exclusive: false,
    note: "A 10-hour night with a friend. That's the whole product. Don't buy it to play alone.",
    cover: "sea",
  },
  {
    slug: "until-dawn",
    title: "Until Dawn",
    year: 2024,
    publisher: "Ballistic Moon",
    genres: ["Horror", "Adventure"],
    moods: ["scare", "friends"],
    msrp: 70,
    street: 40,
    hoursMain: 8,
    hoursExtra: 10,
    hoursComp: 16,
    quality: 7,
    plat: 3,
    exclusive: true,
    note: "A movie with quick-time events. Fine at $20–30. $70 was a joke.",
    cover: "oxblood",
  },
  {
    slug: "death-stranding-2",
    title: "Death Stranding 2",
    year: 2025,
    publisher: "Kojima Productions",
    genres: ["Adventure", "Action", "Open world"],
    moods: ["chill", "story"],
    msrp: 70,
    street: 60,
    hoursMain: 35,
    hoursExtra: 50,
    hoursComp: 70,
    quality: 8,
    plat: 3,
    exclusive: true,
    note: "Long enough to justify the tag if you liked the walk. If you didn't, nothing here converts you.",
    cover: "slate",
  },
  {
    slug: "metaphor",
    title: "Metaphor: ReFantazio",
    year: 2024,
    publisher: "Studio Zero",
    genres: ["RPG"],
    moods: ["story"],
    msrp: 70,
    street: 40,
    hoursMain: 48,
    hoursExtra: 68,
    hoursComp: 90,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Calendar RPG hours, Persona DNA, honest value at $40.",
    cover: "copper",
  },
  {
    slug: "infinite-wealth",
    title: "Like a Dragon: Infinite Wealth",
    year: 2024,
    publisher: "RGG Studio",
    genres: ["RPG", "Adventure"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 30,
    hoursMain: 42,
    hoursExtra: 60,
    hoursComp: 85,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "A vacation that keeps going. $30 is almost irresponsible.",
    cover: "sand",
  },
  {
    slug: "p3r",
    title: "Persona 3 Reload",
    year: 2024,
    publisher: "Atlus",
    genres: ["RPG"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 35,
    hoursMain: 70,
    hoursExtra: 90,
    hoursComp: 110,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Seventy hours of school, tartarus, and feelings. The rate is excellent.",
    cover: "night",
  },
  {
    slug: "hades-2",
    title: "Hades II",
    year: 2025,
    publisher: "Supergiant",
    genres: ["Action", "RPG"],
    moods: ["challenge", "chill"],
    msrp: 30,
    street: 30,
    hoursMain: 25,
    hoursExtra: 40,
    hoursComp: 60,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Priced like a side dish, plays like a main. Instant buy if you like roguelikes.",
    cover: "ember",
  },
  {
    slug: "space-marine-2",
    title: "Warhammer 40,000: Space Marine 2",
    year: 2024,
    publisher: "Saber",
    genres: ["Shooter", "Action", "Co-op"],
    moods: ["friends", "challenge"],
    msrp: 60,
    street: 35,
    hoursMain: 10,
    hoursExtra: 18,
    hoursComp: 30,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "Campaign is a meaty afternoon. Operations are the real hours. Buy for co-op.",
    cover: "steel",
  },
  {
    slug: "doom-dark-ages",
    title: "DOOM: The Dark Ages",
    year: 2025,
    publisher: "id Software",
    genres: ["Shooter", "Action"],
    moods: ["challenge"],
    msrp: 70,
    street: 50,
    hoursMain: 12,
    hoursExtra: 16,
    hoursComp: 22,
    quality: 8,
    plat: 2,
    exclusive: false,
    note: "A 12-hour riot. Wait for $40 unless you still have the campaign soundtrack in your head.",
    cover: "ash",
  },
  {
    slug: "alan-wake-2",
    title: "Alan Wake 2",
    year: 2023,
    publisher: "Remedy",
    genres: ["Horror", "Adventure"],
    moods: ["scare", "story"],
    msrp: 50,
    street: 30,
    hoursMain: 13,
    hoursExtra: 18,
    hoursComp: 25,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "Art-house horror. Short, dense, cheaper now. Worth it if you like being unsettled.",
    cover: "night",
  },
  {
    slug: "control",
    title: "Control Ultimate Edition",
    year: 2020,
    publisher: "Remedy",
    genres: ["Action", "Adventure", "Shooter"],
    moods: ["story", "challenge"],
    msrp: 40,
    street: 15,
    hoursMain: 12,
    hoursExtra: 20,
    hoursComp: 30,
    quality: 9,
    plat: 3,
    exclusive: false,
    note: "The cheapest masterpiece on this list. Just buy it.",
    cover: "slate",
  },
  {
    slug: "rift-apart",
    title: "Ratchet & Clank: Rift Apart",
    year: 2021,
    publisher: "Insomniac",
    genres: ["Platformer", "Adventure", "Action"],
    moods: ["chill"],
    msrp: 70,
    street: 25,
    hoursMain: 12,
    hoursExtra: 15,
    hoursComp: 20,
    quality: 8,
    plat: 2,
    exclusive: true,
    note: "A tech demo that is also a good game. $25 is the number. Platinum is friendly.",
    cover: "frost",
  },
  {
    slug: "lies-of-p",
    title: "Lies of P",
    year: 2023,
    publisher: "Neowiz",
    genres: ["Soulslike", "Action"],
    moods: ["challenge"],
    msrp: 60,
    street: 30,
    hoursMain: 24,
    hoursExtra: 32,
    hoursComp: 45,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "The best Souls-like that isn't From. $30 is almost too low.",
    cover: "bone",
  },
  {
    slug: "armored-core-6",
    title: "Armored Core VI",
    year: 2023,
    publisher: "FromSoftware",
    genres: ["Action", "Shooter"],
    moods: ["challenge"],
    msrp: 60,
    street: 25,
    hoursMain: 15,
    hoursExtra: 25,
    hoursComp: 40,
    quality: 8,
    plat: 4,
    exclusive: false,
    note: "Mechs, missions, replays. A steal if the first hour clicks. A paperweight if it doesn't.",
    cover: "rust",
  },
  {
    slug: "helldivers-2",
    title: "Helldivers 2",
    year: 2024,
    publisher: "Arrowhead",
    genres: ["Shooter", "Co-op"],
    moods: ["friends"],
    msrp: 40,
    street: 40,
    hoursMain: 40,
    hoursExtra: 80,
    hoursComp: 120,
    quality: 8,
    plat: 4,
    exclusive: false,
    note: "Priced like a side game, behaves like a service. Hours only count if your friends show up.",
    cover: "ember",
  },
  {
    slug: "tekken-8",
    title: "Tekken 8",
    year: 2024,
    publisher: "Bandai Namco",
    genres: ["Fighting"],
    moods: ["challenge", "friends"],
    msrp: 70,
    street: 40,
    hoursMain: 8,
    hoursExtra: 20,
    hoursComp: 50,
    quality: 8,
    plat: 4,
    exclusive: false,
    note: "Story is a snack. The game is the ladder. Don't buy it for the campaign.",
    cover: "steel",
  },
  {
    slug: "ff16",
    title: "Final Fantasy XVI",
    year: 2023,
    publisher: "Square Enix",
    genres: ["Action", "RPG", "Adventure"],
    moods: ["story"],
    msrp: 70,
    street: 25,
    hoursMain: 32,
    hoursExtra: 45,
    hoursComp: 60,
    quality: 8,
    plat: 3,
    exclusive: true,
    note: "A long action movie. $25 is the honest tag. Full price never was.",
    cover: "wine",
  },
  {
    slug: "dragons-dogma-2",
    title: "Dragon's Dogma 2",
    year: 2024,
    publisher: "Capcom",
    genres: ["RPG", "Open world", "Action"],
    moods: ["challenge"],
    msrp: 70,
    street: 30,
    hoursMain: 30,
    hoursExtra: 50,
    hoursComp: 80,
    quality: 7,
    plat: 3,
    exclusive: false,
    note: "Weird, stiff, memorable. Buy used. Don't buy twice.",
    cover: "moss",
  },
  {
    slug: "outlaws",
    title: "Star Wars Outlaws",
    year: 2024,
    publisher: "Massive",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 25,
    hoursMain: 17,
    hoursExtra: 28,
    hoursComp: 40,
    quality: 6,
    plat: 2,
    exclusive: false,
    note: "Fine. That's the review. $25 if you want more Star Wars. Not $70.",
    cover: "sand",
  },
  {
    slug: "veilguard",
    title: "Dragon Age: The Veilguard",
    year: 2024,
    publisher: "BioWare",
    genres: ["RPG", "Action"],
    moods: ["story"],
    msrp: 70,
    street: 25,
    hoursMain: 25,
    hoursExtra: 40,
    hoursComp: 55,
    quality: 6,
    plat: 2,
    exclusive: false,
    note: "A softer Dragon Age. Cheap now, which is the only math that works.",
    cover: "frost",
  },
  {
    slug: "nba-2k26",
    title: "NBA 2K26",
    year: 2025,
    publisher: "Visual Concepts",
    genres: ["Sports"],
    moods: ["friends", "chill"],
    msrp: 70,
    street: 50,
    hoursMain: 15,
    hoursExtra: 40,
    hoursComp: 80,
    quality: 5,
    plat: 4,
    exclusive: false,
    note: "A new coat of paint sold as a new game. Wait for a deep sale or skip a year.",
    cover: "steel",
  },
  {
    slug: "suicide-squad",
    title: "Suicide Squad: Kill the Justice League",
    year: 2024,
    publisher: "Rocksteady",
    genres: ["Shooter", "Action"],
    moods: ["friends"],
    msrp: 70,
    street: 10,
    hoursMain: 10,
    hoursExtra: 20,
    hoursComp: 40,
    quality: 4,
    plat: 4,
    exclusive: false,
    note: "The receipt is the review. Ten dollars is still a maybe.",
    cover: "oxblood",
  },
  {
    slug: "forspoken",
    title: "Forspoken",
    year: 2023,
    publisher: "Luminous",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["chill"],
    msrp: 70,
    street: 10,
    hoursMain: 12,
    hoursExtra: 18,
    hoursComp: 25,
    quality: 4,
    plat: 2,
    exclusive: true,
    note: "Parkour is fun for an hour. Everything else is a $10 curiosity.",
    cover: "frost",
  },
  {
    slug: "gta-6",
    title: "Grand Theft Auto VI",
    year: 2026,
    publisher: "Rockstar",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["story", "chill"],
    msrp: 70,
    street: 70,
    hoursMain: 40,
    hoursExtra: 80,
    hoursComp: 120,
    quality: 9,
    plat: 2,
    exclusive: false,
    comingSoon: true,
    estimated: true,
    note: "Not out yet (Nov 19, 2026). Hours are a GTA V-shaped guess. Pre-order only if you already know you'll play it day one.",
    cover: "pine",
  },
  {
    slug: "playroom",
    title: "Astro's Playroom",
    year: 2020,
    publisher: "Team Asobi",
    genres: ["Platformer"],
    moods: ["chill"],
    msrp: 0,
    street: 0,
    hoursMain: 5,
    hoursExtra: 6,
    hoursComp: 8,
    quality: 9,
    plat: 2,
    exclusive: true,
    note: "Free on every PS5. The cost per hour is zero. Play it before you buy another platformer.",
    cover: "sand",
  },
  {
    slug: "rise-of-the-ronin",
    title: "Rise of the Ronin",
    year: 2024,
    publisher: "Team Ninja",
    genres: ["Action", "Open world", "Soulslike"],
    moods: ["challenge"],
    msrp: 70,
    street: 25,
    hoursMain: 25,
    hoursExtra: 40,
    hoursComp: 55,
    quality: 7,
    plat: 3,
    exclusive: true,
    note: "A lot of game, a little too much jank. $25 is the right conversation.",
    cover: "rust",
  },
  {
    slug: "jedi-survivor",
    title: "Star Wars Jedi: Survivor",
    year: 2023,
    publisher: "Respawn",
    genres: ["Action", "Adventure"],
    moods: ["story", "challenge"],
    msrp: 70,
    street: 25,
    hoursMain: 17,
    hoursExtra: 25,
    hoursComp: 35,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "The PS5 version finally behaves. $25 is an easy yes if you liked Fallen Order.",
    cover: "rust",
  },
  {
    slug: "death-stranding-dc",
    title: "Death Stranding Director's Cut",
    year: 2021,
    publisher: "Kojima Productions",
    genres: ["Adventure", "Open world", "Action"],
    moods: ["chill", "story"],
    msrp: 40,
    street: 20,
    hoursMain: 40,
    hoursExtra: 55,
    hoursComp: 80,
    quality: 8,
    plat: 3,
    exclusive: true,
    note: "Play this before DS2. At $20 it is a long, strange bargain.",
    cover: "slate",
  },
  {
    slug: "rdr",
    title: "Red Dead Redemption",
    year: 2024,
    publisher: "Rockstar",
    genres: ["Action", "Open world", "Adventure"],
    moods: ["story", "chill"],
    msrp: 50,
    street: 40,
    hoursMain: 18,
    hoursExtra: 28,
    hoursComp: 40,
    quality: 8,
    plat: 3,
    exclusive: false,
    note: "A classic port, not a remake. Fine if you missed it. RDR2 is still the better receipt.",
    cover: "sand",
  },
];


export const GAMES: Game[] = [...BASE_GAMES, ...EXPANDED_GAMES];

export function costPerHour(game: Pick<Game, "street" | "hoursMain">) {
  if (game.hoursMain <= 0) return 0;
  if (game.street <= 0) return 0;
  return game.street / game.hoursMain;
}

export function fairPriceFor(game: Pick<Game, "hoursMain" | "quality">, targetCph?: number) {
  const sensibleRate = targetCph ?? (game.quality >= 9 ? 3.5 : game.quality >= 8 ? 2.75 : 2);
  return Math.round((game.hoursMain * sensibleRate) / 5) * 5;
}

export function priceDelta(game: Pick<Game, "street" | "hoursMain" | "quality">) {
  return game.street - fairPriceFor(game);
}

export function verdictOf(game: Game): Verdict {
  if (game.comingSoon) return "soon";
  const cph = costPerHour(game);
  if (game.street === 0) return "buy";
  if (game.quality <= 5) return "skip";
  if (game.quality >= 10 && game.hoursMain >= 10) return "buy";
  if (game.quality >= 9 && cph <= 3.6) return "buy";
  if (game.quality >= 8 && cph <= 2.3) return "buy";
  if (game.quality >= 7 && cph <= 1.5) return "buy";
  if (cph >= 6 && game.quality < 8) return "skip";
  if (game.hoursMain <= 8 && game.street >= 40 && game.quality < 9) return "skip";
  return "wait";
}

export function getGame(slug: string) {
  return GAMES.find((g) => g.slug === slug);
}

export function withMath<T extends Game>(game: T) {
  return {
    ...game,
    cph: costPerHour(game),
    fairPrice: fairPriceFor(game),
    priceDelta: priceDelta(game),
    verdict: verdictOf(game),
    discounted: game.msrp > 0 && game.street <= game.msrp * 0.65,
  };
}

export type GameMath = ReturnType<typeof withMath>;

export const CATALOG = GAMES.map(withMath);

export function rankedByValue(list = CATALOG) {
  return [...list].sort((a, b) => a.cph - b.cph);
}

export function searchGames(q: string, list = CATALOG) {
  const needle = q.trim().toLowerCase();
  if (!needle) return list;
  return list.filter((g) => {
    const hay = `${g.title} ${g.publisher} ${g.genres.join(" ")}`.toLowerCase();
    return hay.includes(needle);
  });
}

export const VERDICT_COPY: Record<Verdict, { label: string; line: string }> = {
  buy: { label: "BUY", line: "The hours justify the tag." },
  wait: { label: "WAIT", line: "A sale will fix this receipt." },
  skip: { label: "SKIP", line: "Pay this and you're buying the box, not the hours." },
  soon: { label: "SOON", line: "Not out yet. Hours are an estimate." },
};

export const PLAT_COPY = [
  "",
  "Friendly",
  "Doable",
  "A project",
  "A grind",
  "A second job",
] as const;
